[EnumSecurity]
constraint = "SecurityType"
[EnumSecurity.Variants]
WPA2Personal   = "WPA2PersonalData"
WPA2Enterprise = "WPA2EnterpriseData"

[CPEInterfaceInfo]
constraint = "CPEInterfaceType"
[CPEInterfaceInfo.Variants]
Wired = "WiredData"
WiFi  = "WiFiData"

[CPEAgentError]
constraint = "CPEAgentStatusType"
[CPEAgentError.Variants]
Success     = "null"
Undefined   = "string"
SyntaxError = "string"
Exception   = "string"

[SystemEventObject]
constraint = "SystemEventType"
[SystemEventObject.Variants]
CPEConnected            = "CPEConnectedData"
CPEDisconnected         = "null"
MonitorRuleViolation    = "MonitorRuleViolationData"
CPEConfigurationError   = "CPEConfigurationErrorData"
CPEConfigurationSuccess = "null"
ClientConnected         = "ClientConnectedData"
ClientDisconnected      = "ClientDisconnectedData"
ServiceFatalError       = "ServiceFatalErrorData"
ServiceConnected        = "ServiceConnectedData"
ServiceDisconnected     = "null"
DaemonSettingsChanged   = "null"

[StatEventRuleObject]
constraint = "StatEventRuleType"
[StatEventRuleObject.Variants]
FreeRAM = "LimitBetween"
CPUload = "LimitBetween"

[WirelessClientObject]
constraint = "WirelessClientType"
[WirelessClientObject.Variants]
Camera = "CameraClientData"
Other = "OtherClientData"
