[EnumSecurity]
constraint = "SecurityType"
[EnumSecurity.Variants]
WPA2Personal = "WPA2PersonalData"
WPA2Enterprise = "WPA2EnterpriseData"

[CPEInterfaceInfo]
constraint = "CPEInterfaceType"
[CPEInterfaceInfo.Variants]
InterfaceWired = "WiredData"
InterfaceWiFi = "WiFiData"

[CPEAgentError]
constraint = "CPEAgentStatusType"
[CPEAgentError.Variants]
CPEAgentStatusSuccess = "goutil.Document"
CPEAgentStatusUndefined   = "string"
CPEAgentStatusSyntaxError = "string"
CPEAgentStatusException   = "string"

[StatEventRule]
constraint = "StatEventRuleType"
[StatEventRule.Variants]
StatEventFreeRAM = "LimitBetween"
StatEventCPUload = "LimitBetween"
