[EnumSecurity]
constraint = "SecurityType"
[EnumSecurity.Variants]
WPA2Personal   = "WPA2PersonalData"
WPA2Enterprise = "WPA2EnterpriseData"
WPAPersonal    = "WPAPersonalData"
WPAEnterprise  = "WPAEnterpriseData"
None           = "null"

[SystemEventObject]
constraint = "SystemEventType"
[SystemEventObject.Variants]
CPEConnected            = "CPEConnectedData"
CPEDisconnected         = "null"
MonitorRuleViolation    = "MonitorRuleViolationData"
ClientConnected         = "ClientConnectedData"
ClientDisconnected      = "ClientDisconnectedData"
ServiceFatalError       = "ServiceFatalErrorData"
ServiceConnected        = "ServiceConnectedData"
ServiceDisconnected     = "null"
DaemonSettingsChanged   = "null"
WLANCentrAccChanged     = "WLANCentrAccChangeData"
SystemTimeChanged       = "null"
CPEInterfaceState       = "CPEInterfaceStateData"
RRMStatus               = "RRMStatusData"
FirmwareUploaded        = "FirmwareUploadedData"
CpeFirmwareAvailable    = "CpeFirmwareData"
RadiusAccountingSend    = "RadiusAccountingSendData"
LoggedError             = "ModelError"

[StatEventRuleObject]
constraint = "StatEventRuleType"
[StatEventRuleObject.Variants]
FreeRAM = "LimitBetween"
CPUload = "LimitBetween"

[WirelessClientObject]
constraint = "WirelessClientType"
[WirelessClientObject.Variants]
Camera = "CameraClientData"
Wired  = "OtherClientData"
Other  = "OtherClientData"

[RadiusMessageObject]
constraint = "RadiusMessageType"
[RadiusMessageObject.variants]
AccountingRequest = "RadiusAccountingRequest"
AccessRequest     = "RadiusAccessRequest"
AccessAccept      = "RadiusAccessAccept"
AccessReject      = "RadiusAccessReject"