[EnumSecurity]
constraint = "SecurityType"
[EnumSecurity.Variants]
WPA2Personal   = "WPA2PersonalData"
WPA2Enterprise = "WPA2EnterpriseData"
WPAPersonal    = "WPAPersonalData"
WPAEnterprise  = "WPAEnterpriseData"
None           = "null"

[SystemEventObject]
constraint = "SystemEventType"
[SystemEventObject.Variants]
CPEConnected            = "CPEConnectedData"
CPEDisconnected         = "null"
MonitorRuleViolation    = "MonitorRuleViolationData"
ClientConnected         = "ClientConnectedData"
ClientDisconnected      = "ClientDisconnectedData"
ServiceFatalError       = "ServiceFatalErrorData"
ServiceConnected        = "ServiceConnectedData"
ServiceDisconnected     = "null"
DaemonSettingsChanged   = "null"
WLANCentrAccChanged     = "WLANCentrAccChangeData"
SystemTimeChanged       = "null"
CPEInterfaceState       = "CPEInterfaceStateData"
RRMStatus               = "RRMStatusData"
FirmwareUploaded        = "FirmwareUploadedData"
CpeFirmwareAvailable    = "CpeFirmwareData"
RadiusAccountingSend    = "RadiusAccountingSendData"
LoggedError             = "ModelError"
RadarExportUpdate       = "RadarExportUpdate"
ClientAuthorization     = "ClientAuthorizationData"
DHCPAck                 = "DHCPAckData"

[StatEventRuleObject]
constraint = "StatEventRuleType"
[StatEventRuleObject.Variants]
FreeRAM      = "LimitBetween"
CPUload      = "LimitBetween"
Connected    = "null"
Disconnected = "null"
ConfigError  = "null"
IfaceError   = "null"
ClientCon    = "null"
ClientDis    = "null"
ClientFar    = "LimitBetween"
CustomerActivity = "LimitBetween"


[WirelessClientObject]
constraint = "WirelessClientType"
[WirelessClientObject.Variants]
Camera = "CameraClientData"
Wired  = "OtherClientData"
Other  = "OtherClientData"

[RadiusMessageObject]
constraint = "RadiusMessageType"
[RadiusMessageObject.variants]
AccountingRequest = "RadiusAccountingRequest"
AccessRequest     = "RadiusAccessRequest"
AccessAccept      = "RadiusAccessAccept"
AccessReject      = "RadiusAccessReject"

[RRMAlgoObject]
constraint = "RRMAlgoType"
[RRMAlgoObject.variants]
Dummy = "RRMTimerParams"
Blind = "RRMTimerParams"
Greed = "RRMGreedParams"
