[EnumSecurity]
constraint = "SecurityType"
[EnumSecurity.Variants]
WPA2Personal   = "WPA2PersonalData"
WPA2Enterprise = "WPA2EnterpriseData"
WPAPersonal    = "WPAPersonalData"
WPAEnterprise  = "WPAEnterpriseData"
None           = "null"

[SystemEventObject]
constraint = "SystemEventType"
[SystemEventObject.Variants]
CPEConnected            = "CPEConnectedData"
CPEDisconnected         = "null"
MonitorRuleViolation    = "MonitorRuleViolationData"
CPEConfigurationError   = "CPEConfigurationErrorData"
CPEConfigurationSuccess = "null"
ClientConnected         = "ClientConnectedData"
ClientDisconnected      = "ClientDisconnectedData"
ServiceFatalError       = "ServiceFatalErrorData"
ServiceConnected        = "ServiceConnectedData"
ServiceDisconnected     = "null"
DaemonSettingsChanged   = "null"
WLANCentrAccChanged     = "WLANCentrAccChangeData"
SystemTimeChanged       = "null"
CPEInterfaceState       = "CPEInterfaceStateData"
RRMStatus               = "RRMStatusData"
FirmwareUploaded        = "FirmwareUploadedData"
CpeFirmwareAvailable    = "CpeFirmwareData"

[StatEventRuleObject]
constraint = "StatEventRuleType"
[StatEventRuleObject.Variants]
FreeRAM = "LimitBetween"
CPUload = "LimitBetween"

[WirelessClientObject]
constraint = "WirelessClientType"
[WirelessClientObject.Variants]
Camera = "CameraClientData"
Other = "OtherClientData"

[RadiusAccountingObject]
constraint = "ClientStatPacketType"
[RadiusAccountingObject.variants]
Start   = "RadiusAccountingStart"
Stop    = "RadiusAccountingStop"
Interim = "RadiusAccountingInterim"
On      = "null"
Off     = "null"