[EnumSecurity]
constraint = "SecurityType"
[EnumSecurity.Variants]
WPA2Personal = "WPA2PersonalData"
WPA2Enterprise = "WPA2EnterpriseData"

[CPEInterfaceInfo]
constraint = "CPEInterfaceType"
[CPEInterfaceInfo.Variants]
InterfaceWired = "WiredData"
InterfaceWiFi = "WiFiData"

[CPEAgentError]
constraint = "CPEAgentStatusType"
[CPEAgentError.Variants]
CPEAgentStatusSuccess     = "null"
CPEAgentStatusUndefined   = "string"
CPEAgentStatusSyntaxError = "string"
CPEAgentStatusException   = "string"

[StatEventRuleObject]
constraint = "StatEventRuleObjectType"
[StatEventRuleObject.Variants]
StatEventFreeRAM = "LimitBetween"
StatEventCPUload = "LimitBetween"

[WirelessClientObject]
constraint = "WirelessClientObjectType"
[WirelessClientObject.Variants]
CameraClient = "CameraClient"
OtherClient = "OtherClient"
