[ConfigurationStatus]
default = "Empty"
[ConfigurationStatus.variants]
Empty    = "empty"
Error    = "error"
OK       = "ok"
Pending  = "pending"
Updating = "updating"

[Module]
[Module.variants]
Any        = "+"
Dummy      = "DUMMY"
Backend    = "BACKEND"
CPE        = "CPE"
Config     = "CONFIG"
DB         = "DB"
Stat       = "STAT"
Monitor    = "MONITOR"
LBS        = "LBS"
ClientStat = "CLIENT_STAT"
MQTTLog    = "MQTT_LOG"
CPEStat    = "CPE_STAT"
AC         = "AC"
TunManager = "TUN_MANAGER"
RRM        = "RRM"
FW         = "FW"
Redirect   = "REDIRECT"
PortalBack = "PORTAL_BACKEND"

[Operation]
[Operation.variants]
Any       = "+"
Create    = "C"
Delete    = "D"
Read      = "R"
Update    = "U"
LuaScript = "LUA"
SHScript  = "SH"
CPEStatus = "STATUS"
JSONRPC   = "JSONRPC"

[SystemEventType]
[SystemEventType.variants]
Any                     = "+"
CPEConnected            = "CPE_CONNECTED"
CPEDisconnected         = "CPE_DISCONNECTED"
MonitorRuleViolation    = "MONITOR_RULE_VIOLATION"
CPEConfigurationError   = "CPE_CONFIGURATION_ERROR"
CPEConfigurationSuccess = "CPE_CONFIGURATION_SUCCESS"
CPEInterfaceState       = "CPE_INTERFACE_STATE"
ClientConnected         = "CLIENT_CONNECTED"
ClientDisconnected      = "CLIENT_DISCONNECTED"
ServiceFatalError       = "SERVICE_FATAL_ERROR"
ServiceConnected        = "SERVICE_CONNECTED"
ServiceDisconnected     = "SERVICE_DISCONNECTED"
DaemonSettingsChanged   = "DAEMON_SETTINGS_CHANGE"
WLANCentrAccChanged     = "WLAN_CENTR_ACC_CHANGE"
SystemTimeChanged       = "SYSTEM_TIME_CHANGE"
RRMStatus               = "RRM_STATUS_DATA"

[SystemEventLevel]
default = "DEBUG"
[SystemEventLevel.variants]
INFO      = "INFO"
DEBUG     = "DEBUG"
ERROR     = "ERROR"
WARNING   = "WARNING"

[SecuritySuite]
[SecuritySuite.variants]
AES  = "aes"
TKIP = "tkip"

[SecurityType]
default = "None"
[SecurityType.variants]
WPA2Enterprise = "wpa2enterprise"
WPA2Personal   = "wpa2personal"
WPAEnterprise  = "wpaenterprise"
WPAPersonal    = "wpapersonal"
None           = "open"

[CPEAgentStatusType]
default = "Undefined"
[CPEAgentStatusType.variants]
Success     = "success"
Undefined   = "undefined"
SyntaxError = "syntax"
Exception   = "exception"

[StatEventRuleType]
[StatEventRuleType.variants]
FreeRAM = "free_ram"
CPUload = "cpu_load"

[ClientStatPacketType]
[ClientStatPacketType.variants]
On      = "Accounting-On"
Off     = "Accounting-Off"
Start   = "Start"
Stop    = "Stop"
Interim = "Interim-Update"

[WirelessClientType]
default = "Other"
[WirelessClientType.variants]
Camera = "camera"
Other  = "other"

[WirelessClientState]
[WirelessClientState.variants]
CONNECTED     = "CONNECTED"
DISCONNECTED  = "DISCONNECTED"

[ConnectionModeType]
default = "ModeLegacy"
[ConnectionModeType.variants]
ModeAC      = "ac"
ModeN       = "n"
ModeLegacy  = "legacy"

[MacFilterType]
default = "None"
[MacFilterType.variants]
BlackList = "BlackList"
WhiteList = "WhiteList"
None      = "None"

[ServiceState]
[ServiceState.variants]
Connected    = "CONNECTED"
Disconnected = "DISCONNECTED"
Pending      = "PENDING"

[CPEInterfaceState]
[CPEInterfaceState.variants]
Enabled       = "ENABLED"
Disabled      = "DISABLED"
ACS           = "ACS"
DFS           = "DFS"
CountryUpdate = "CONTRY_UPDATE"
HtScan        = "HT_SCAN"
Unknown       = "UNKNOWN"
Uninitialized = "UNINITIALIZED"
Terminated    = "TERMINATED"

[TunManagerRPC]
[TunManagerRPC.variants]
CreateL2TunnelSession = "CreateL2TunnelSession"
DeleteL2TunnelSession = "DeleteL2TunnelSession"

[MCSRequire]
default = "Off"
[MCSRequire.variants]
Off = "off"
HT  = "ht"
VHT = "vht"

[FirewallPolicy]
default = "Empty"
[FirewallPolicy.variants]
Empty  = ""
Drop   = "DROP"
Accept = "ACCEPT"

[L3Protocol]
default = "Empty"
[L3Protocol.variants]
Empty = ""
IP    = "ip"
IPv4  = "ipv4"
IPv6  = "ipv6"

[L4Protocol]
default = "Empty"
[L4Protocol.variants]
Empty = ""
TCP   = "TCP"
UDP   = "UDP"

[FirewallJump]
default = "Accept"
[FirewallJump.variants]
Accept = "ACCEPT"
DROP   = "DROP"


[FirewallDirection]
default = "Any"
[FirewallDirection.variants]
Any = "ANY"
In  = "IN"
Out = "OUT"

[FirmwareUpdateMode]
default = "On"
[FirmwareUpdateMode.variants]
On    = "on"
Off   = "off"
Check = "check"

[PortalAuthType]
default = "None"
[PortalAuthType.variants]
None     = ""
RADIUS   = "radius"
SMS      = "sms"
OAuth2   = "oauth2"
External = "external"
