[ConfigurationStatus]
default = "Empty"
[ConfigurationStatus.variants]
Empty     = "empty"
OK        = "ok"
Offline   = "offline"
Updating  = "updating"
Upgrading = "upgrading"
Rebooting = "rebooting"
DontUse1  = "pending"
DontUse2  = "error"

[Module]
default = "None"
[Module.variants]
Any        = "+"
None       = ""
Dummy      = "DUMMY"
Backend    = "BACKEND"
CPE        = "CPE"
Config     = "CONFIG"
DB         = "DB"
Stat       = "STAT"
Monitor    = "MONITOR"
LBS        = "LBS"
ClientStat = "CLIENT_STAT"
MQTTLog    = "MQTT_LOG"
CPEStat    = "CPE_STAT"
AC         = "AC"
TunManager = "TUN_MANAGER"
RRM        = "RRM"
FW         = "FW"
Redirect   = "REDIRECT"
PortalBack = "PORTAL_BACKEND"
RadiusGw   = "RADIUS_GATEWAY"
Mediator   = "MEDIATOR"
StatLBS    = "STAT-LBS"
AnalMW     = "ANAL-MW"
RadarMW    = "RADAR-MW"
RadarExportMW  = "RADAR-EXPORT-MW"
ClientDistance = "CLIENT-DISTANCE"
Resampling = "RESAMPLING"
SnmpWalker = "SNMP_WALKER"
CLI        = "CLI"
GSNMP      = "GSNMP"
SessionManager = "SESSION_MANAGER"

[Operation]
[Operation.variants]
Any       = "+"
Create    = "C"
Delete    = "D"
Read      = "R"
Update    = "U"
LuaScript = "LUA"
SHScript  = "SH"
CPEStatus = "STATUS"
JSONRPC   = "JSONRPC"

[SystemEventType]
[SystemEventType.variants]
Any                     = "+"
CPEConnected            = "CPE_CONNECTED"
CPEDisconnected         = "CPE_DISCONNECTED"
MonitorRuleViolation    = "MONITOR_RULE_VIOLATION"
CPEInterfaceState       = "CPE_INTERFACE_STATE"
ClientConnected         = "CLIENT_CONNECTED"
ClientDisconnected      = "CLIENT_DISCONNECTED"
ServiceFatalError       = "SERVICE_FATAL_ERROR"
ServiceConnected        = "SERVICE_CONNECTED"
ServiceDisconnected     = "SERVICE_DISCONNECTED"
DaemonSettingsChanged   = "DAEMON_SETTINGS_CHANGE"
WLANCentrAccChanged     = "WLAN_CENTR_ACC_CHANGE"
SystemTimeChanged       = "SYSTEM_TIME_CHANGE"
RRMStatus               = "RRM_STATUS_DATA"
FirmwareUploaded        = "FIRMWARE_UPLOADED"
CpeFirmwareAvailable    = "CPE_FIRMWARE_AVAILABLE"
RadiusAccountingSend    = "RADIUS_ACCOUNTING_SEND"
LoggedError             = "LOGGED_ERROR"
UserAuthSuccess         = "USER_AUTHORIZATION_SUCCESS"
RadarExportUpdate       = "RADAR_EXPORT_UPDATE"
ClientAuthorization     = "CLIENT_AUTHORIZATION"
DHCPAck                 = "DHCP_ACK"
LocationCacheReload     = "LOCATION_CACHE_RELOAD"
RRMGroupApplyAlgo       = "RRM_GROUP_APPLY_ALGO"

[SystemEventLevel]
default = "DEBUG"
[SystemEventLevel.variants]
INFO      = "INFO"
DEBUG     = "DEBUG"
ERROR     = "ERROR"
WARNING   = "WARNING"

[SecuritySuite]
[SecuritySuite.variants]
AES  = "aes"
TKIP = "tkip"
CCMP = "ccmp"

[SecurityType]
default = "None"
[SecurityType.variants]
WPA2Enterprise = "wpa2enterprise"
WPA2Personal   = "wpa2personal"
WPAEnterprise  = "wpaenterprise"
WPAPersonal    = "wpapersonal"
None           = "open"
WPA3Enterprise = "wpa3enterprise"
WPA3Personal   = "wpa3personal"
WPA23Personal  = "wpa23personal"
WPA23Enterprise= "wpa23enterprise"

[CPEAgentStatusType]
default = "Undefined"
[CPEAgentStatusType.variants]
Success     = "success"
Undefined   = "undefined"
SyntaxError = "syntax"
Exception   = "exception"

[StatEventRuleType]
[StatEventRuleType.variants]
FreeRAM      = "free_ram"
CPUload      = "cpu_load"
Connected    = "connected"
Disconnected = "disconnected"
ConfigError  = "config_error"
IfaceError   = "iface_error"
ClientCon    = "client_con"
ClientDis    = "client_dis"
ClientFar    = "client_far"
CustomerActivity = "customer_activity"

[ClientStatPacketType]
[ClientStatPacketType.variants]
OnOld      = "Accounting-On"
OffOld     = "Accounting-Off"
StartOld   = "Start"
StopOld    = "Stop"
InterimOld = "Interim-Update"
Start      = "start"
Stop       = "stop"
Interim    = "interim"

[WirelessClientType]
default = "Other"
[WirelessClientType.variants]
Camera = "camera"
Other  = "other"
Wired  = "wired"

[WirelessClientState]
[WirelessClientState.variants]
Connected     = "CONNECTED"
Disconnected  = "DISCONNECTED"

[ConnectionModeType]
default = "ModeLegacy"
[ConnectionModeType.variants]
ModeAC      = "ac"
ModeN       = "n"
ModeLegacy  = "legacy"
ModeAX      = "ax"

[MacFilterType]
default = "None"
[MacFilterType.variants]
BlackList = "BlackList"
WhiteList = "WhiteList"
None      = "None"

[ServiceState]
[ServiceState.variants]
Connected    = "CONNECTED"
Disconnected = "DISCONNECTED"
Pending      = "PENDING"

[CPEInterfaceState]
[CPEInterfaceState.variants]
Enabled       = "ENABLED"
Disabled      = "DISABLED"
ACS           = "ACS"
DFS           = "DFS"
CountryUpdate = "COUNTRY_UPDATE"
HtScan        = "HT_SCAN"
Unknown       = "UNKNOWN"
Uninitialized = "UNINITIALIZED"
Terminated    = "TERMINATED"

[TunManagerRPC]
[TunManagerRPC.variants]
CreateL2TunnelSession = "CreateL2TunnelSession"
DeleteL2TunnelSession = "DeleteL2TunnelSession"

[MCSRequire]
default = "Off"
[MCSRequire.variants]
Off = "off"
HT  = "ht"
VHT = "vht"

[FirewallPolicy]
default = "Empty"
[FirewallPolicy.variants]
Empty  = ""
Drop   = "DROP"
Accept = "ACCEPT"
Return = "RETURN"

[L3Protocol]
default = "Empty"
[L3Protocol.variants]
Empty = ""
IP    = "ip"
IPv4  = "ipv4"
IPv6  = "ipv6"

[L4Protocol]
default = "Empty"
[L4Protocol.variants]
Empty = ""
TCP   = "TCP"
UDP   = "UDP"

[FirewallDirection]
default = "Any"
[FirewallDirection.variants]
Any = "ANY"
In  = "IN"
Out = "OUT"

[FirmwareUpdateMode]
default = "Check"
[FirmwareUpdateMode.variants]
On    = "on"
Off   = "off"
Check = "check"

[PortalAuthType]
default = "None"
[PortalAuthType.variants]
None     = ""
RADIUS   = "radius"
SMS      = "sms"
OAuth2   = "oauth2"
External = "external"

[RadiusMessageType]
default = "AccountingRequest"
[RadiusMessageType.variants]
AccountingRequest = "accounting"
AccessRequest     = "access-request"
AccessAccept      = "access-accept"
AccessReject      = "access-reject"

[RRMAlgoType]
default = "Greed"
[RRMAlgoType.variants]
Dummy = "Dummy"
Blind = "Blind"
Greed = "Greed"

[WMMAccessCategory]
default = "Background"
[WMMAccessCategory.variants]
Background = "BK"
BestEffort = "BE"
Video = "VI"
Voice = "VO"

[ControllerStatusType]
default = "Empty"
[ControllerStatusType.variants]
Empty        = "empty"
Error        = "error"
Connected    = "connected"
Disconnected = "disconnected"
Updating     = "updating"
Provisioning = "provision"

[RadarExportType]
default = "Email"
[RadarExportType.variants]
Email    = "email"
Yandex   = "yandex"
Mytarget = "mytarget"
External = "external"
BeePro   = "beepro"

[RadarExportFormat]
default = "CSV"
[RadarExportFormat.variants]
CSV      = "csv"
Json     = "json"
Txt      = "txt"

[RadarExportFilter]
default = "All"
[RadarExportFilter.variants]
All     = "all"
New     = "new"
Return  = "return"

[RadarExportStatus]
default = "Created"
[RadarExportStatus.variants]
Created  = "created"
Updated  = "updated"
Running  = "running"
Finished = "finished"

[RadarExportMacs]
default = "All"
[RadarExportMacs.variants]
All   = "all"
Real  = "real"
Fake  = "fake"

[SpeedType]
default = "Kbit"
[SpeedType.variants]
Kbit = "kbit"
Mbit = "mbit"
Gbit = "gbit"
Tbit = "tbit"

[PortalProfileType]
default = "Free"
[PortalProfileType.variants]
Free     = "free"
Sponsor  = "sponsor"
Premium  = "premium"

[ReportPeriod]
default = "Now"
[ReportPeriod.variants]
Now   = "now"
Day   = "day"
Week  = "week"
Month = "month"

[ReportActionType]
default = "Email"
[ReportActionType.variants]
Email  = "email"
Script = "script"

[ReportFormat]
default = "Json"
[ReportFormat.variants]
CSV      = "csv"
Json     = "json"
Txt      = "txt"
XLSX     = "xlsx"

[ReportType]
default = "Current"
[ReportType.variants]
Current = "current"
Summary = "summary"
ClientsAll = "clients"
ClientsAuthorized = "clients_auth"

[ReportSubject]
default = "Clients"
[ReportSubject.variants]
Clients   = "clients"
CPEs      = "cpes"
Events    = "events"
CPECommon = "cpes_common"

[TunnelType]
default = "L2TP"
[TunnelType.variants]
L2TP  = "l2tpv3"
EoGRE = "gretap"
GRE   = "gre"

[NotifyType]
default = "Empty"
[NotifyType.variants]
Empty  = ""
Telegram  = "telegram"
Email = "email"
Mqtt   = "mqtt"

[Option82CircuitIDType]
default="Empty"
[Option82CircuitIDType.variants]
Empty=""
Ssid="SSID"
Ifname="IFNAME"

[Option82RemoteIDType]
default="ApMacSSID"
[Option82RemoteIDType.variants]
ApMacSSID="APMAC:SSID"
WlanIFName="WLAN:IFNAME"
VlanSSID="VLAN:SSID"
BSSIDHostname="BSSID:HOSTNAME"
ApMacSiteID="APMAC:SITEID"
ApMac="APMAC"

[OperationStatus]
[OperationStatus.variants]
Success = "success"
Error   = "error"
Pending = "pending"

[SNMPAccessMode]
default = "Read"
[SNMPAccessMode.variants]
Read = "read"
ReadWrite = "read/write"

[SNMPSecurityLevelType]
default="NoAuthNoPriv"
[SNMPSecurityLevelType.variants]
NoAuthNoPriv = "noAuthNoPriv"
AuthNoPriv = "authNoPriv"
AuthPriv = "authPriv"

[SNMPAuthProtocol]
default="MD5"
[SNMPAuthProtocol.variants]
MD5="MD5"
SHA="SHA"
SHA224="SHA-224"
SHA256="SHA-256"
SHA384="SHA-384"
SHA512="SHA-512"

[SNMPPrivacyProtocol]
default="DES"
[SNMPPrivacyProtocol.variants]
DES="DES"
AES="AES"
AES192="AES-192"
AES256="AES-256"

[SNMPVersion]
default="V1"
[SNMPVersion.variants]
V1="1"
V2="2c"
V3="3"

[NTPGeneralActive]
default="NotActive"
[NTPGeneralActive.variants]
NotActive="not active"
Active="active"

[NTPServerStatus]
default="Unsyncronized"
[NTPServerStatus.variants]
Unsyncronized="unsyncronized"
Configured="configured"
Peer="peer"

[RadioActiveState]
default="Stop"
[RadioActiveState.variants]
Stop="stop"
Start="start"


[Model]
[Model.variants]
WLAN         	   = "wlan"
CPE 	     	   = "cpe"
RADIUS       	   = "radius"
Operation    	   = "operation"
User         	   = "user"
Location     	   = "location"
BaseLocation       = "base_location"
MonitorRules 	   = "stat-event-rule"
MonitorCPE   	   = "poll-cpe"
MonitorEvents      = "event-stat-rule-violation"
CPEStats           = "stat"
ClientStats        = "client-stat"
ClientList         = "client-list"
ClientStatExt      = "client-stat-ext"
LBSCPEInfo         = "lbs-cpe-info"
LBSClientCoord     = "lbs-client-coords"
LBSClientTrack     = "lbs-client-track"
Client             = "client"
CPEMap             = "mapobjects"
CPEMapPosition     = "cpe_map_position"
CPEMapScale        = "cpe_map_scale"
CPEMapCPEList      = "cpe_map_cpe_list"
CommonDashboard    = "common_dashboard"
CompactDashboard   = "compact_dashboard"
SystemDashboard    = "system_dashboard"
ClientDashboard    = "client_dashboard"
WlanDashboard      = "wlan_dashboard"
CPEDashboard       = "cpe_dashboard"
CommonEvents       = "common_events"
SystemEvents       = "system_events"
CPEEvents          = "cpe_events"
MoniEvents         = "monitor_events"
ClientEvents       = "client_events"
Configuration      = "configuration"
HeatMapTraffic     = "heatmap_traffic"
HeatMapClients     = "heatmap_clients"
HeatMapLBSClients  = "heatmap_lbs_clients"
SystemCPEStats     = "system_cpe_stats"
WLANStats          = "wlans_stats"
SystemCPERateStats = "system_cpe_rate_stats"
WLANRateStats      = "wlans_rate_stats"
WLANRating         = "wlan_rating"
WLANClientRating   = "wlan_client_rating"
CPERating          = "cpe_rating"
BSSRating          = "bss_rating"
ClientRating       = "client_rating"
SystemRating       = "system_rating"
WLANTimeline       = "wlan_timeline"
CPETimeline        = "cpe_timeline"
ClientTimeline     = "client_timeline"
SystemTimeline     = "system_timeline"
WLANCPETimeline    = "wlan_cpe_timeline"
WLANClientTimeline = "wlan_client_timeline"
License            = "license"
CPERemote          = "cpe_remote"
CPESession         = "cpe_session"
ClientSession      = "client_session"
WLANCurrentState   = "wlan_current_state"
CPECurrentState    = "cpe_current_state"
ClientCurrentState = "client_current_state"
CPESessionAvg      = "cpe_session_avg"
WLANSessionAvg     = "wlan_session_avg"
ClientSessionAvg   = "client_session_avg"
CPEScanLast        = "cpe_scan_last"
Host               = "host"
CPETags            = "cpe_tags"
CPEReport          = "cpe_report"
LoaderSettings     = "settings_loader"
LoaderTask         = "periodic_task"
WLANTags           = "wlan_tags"
CPEAggStat         = "cpe_agg_stats"
WLANAggStat        = "wlan_agg_stats"
WLANCPEAggStat     = "wlan_cpe_agg_stats"
CPEWLANAggStat     = "cpe_wlan_agg_stats"
CPEModels          = "cpe_models"
CPEConfigTemplates = "cpe_config_templates"
L2Chain            = "l2-chain"
CPEFWUpgrade       = "cpe_fw_upgrade"
CaptiveRedirect    = "captive-redirect"
LBSClientData      = "lbs-client-data"
LBSClientProbes    = "lbs-client-probes"
HotspotProfile     = "hotspot-profile"
RRMGroups          = "rrm-groups"
Controller         = "controller"
ExternalAP         = "ext_access_point"
RadarExport        = "radar_exports"
StatReport         = "report"
ClientRF           = "client_rf"
ClientDistance     = "client_distance"
LicenseLogDaily    = "license_log_daily"
DitExport          = "dit_export"
Resampling         = "resampling"
LBSZones           = "lbs_zones"
SnmpWalker         = "snmp_walker"

[Coll]
[Coll.variants]
WLAN         	  = "wlans"
CPE 	     	  = "cpes"
RADIUS       	  = "radius"
Operation    	  = "operation"
User         	  = "user"
Location     	  = "location"
ClientStats       = "client_stats"
BaseLocation      = "base_location"
MonitorRules 	  = "stat_event_rule"
MonitorCPE   	  = "poll_cpe"
MonitorEvents     = "events"
CPEStats          = "stats"
CPEMap            = "cpe_maps"
LBSCPEInfo        = "lbs_cpe_info"
LBSClientCoord    = "lbs_client_coords"
LBSClientData     = "lbs_client_data"
Clients           = "clients"
CPEStatInfo 	  = "cpe_stat_info"
BSSStatInfo       = "bss_stat_info"
WLANStatInfo      = "wlan_stat_info"
ClientStatInfo    = "client_stat_info"
CPESessionInfo    = "cpe_session_info"
Tags              = "tags"
CPEModel          = "cpe_model"
CPEConfigTemplate = "config_rule"
L2Chain           = "l2_chains"
CaptiveRedirect   = "captive_redirects"
LBSClientProbes   = "lbs_client_probes"
HotspotProfiles   = "hotspot_profile"
RRMGroups         = "rrm_groups"
ClientSession     = "client_session_info"
Controller        = "controllers"
ExternalAP        = "ext_access_points"
StatReport        = "reports"
ReportResult      = "report_results"
ClientRF          = "client_rf"
ClientDistance    = "client_distance"
LicenseLogDaily   = "license_log_daily"
ResamplingConf    = "resampling_conf"
CollLBSZones      = "lbs_zones"
SnmpWalker        = "snmp_walker"
RadarProbesRaw    = "radar_probes_raw"
RadarProbesReal   = "radar_probes_real"
RadarVisits       = "radar_visits"
RadarVisitsFirst  = "radar_visits_first"
RadarVisitsHour   = "radar_visits_hour"
RadarExport       = "radar_export"
RadarExportResult = "radar_export_result"
SnmpGeneral       = "snmp_general"
SnmpCommunity     = "snmp_community"
SnmpUsersGroup    = "snmp_user_group"
SnmpUsers         = "snmp_users"
SnmpHosts         = "snmp_hosts"
WLCConfigs        = "wlc_configs"
NTPConfig         = "ntp_config"
Troubleshooting   = "troubleshooting"
NtpServers        = "ntp_servers"
NtpTimeSettings   = "ntp_time_settings"
