[CPEInterfaceType]
prefix = "Interface"
[CPEInterfaceType.variants]
WiFi    = { string = "wifi"  }
Wired   = { string = "wired" }

[ConfigurationStatus]
prefix = "Status"
[ConfigurationStatus.variants]
Empty   = { string = "empty"   }
Error   = { string = "error"   }
OK      = { string = "ok"      }
Pending = { string = "pending" }

[Module]
prefix = "Module"
[Module.variants]
Any     = { string = "+"       }
Backend = { string = "BACKEND" }
CPE     = { string = "CPE"     }
Config  = { string = "CONFIG"  }
DB      = { string = "DB"      }
Stat    = { string = "STAT"    }

[Operation]
prefix = "Operation"
[Operation.variants]
Any       = { string = "+"   }
Create    = { string = "C"   }
Delete    = { string = "D"   }
Read      = { string = "R"   }
Update    = { string = "U"   }
LuaScript = { string = "LUA" }
SHScript  = { string = "SH"  }

[RadiusType]
prefix = "Radius"
[RadiusType.variants]
Accounting     = { string = "acc"  }
Authentication = { string = "auth" }
Both           = { string = "both" }

[SecuritySuite]
[SecuritySuite.variants]
AES  = { string = "aes"  }
TKIP = { string = "tkip" }

[SecurityType]
[SecurityType.variants]
WPA2Enterprise = { string = "wpa2enterprise" }
WPA2Personal   = { string = "wpa2personal"   }

[CPEAgentStatusType]
prefix = "CPEAgentStatus"
[CPEAgentStatusType.variants]
Success     = { string = "success"   }
Undefined   = { string = "undefined" }
SyntaxError = { string = "syntax"    }
Exception   = { string = "exception" }

[StatEventRuleType]
prefix = "StatEvent"
[StatEventRuleType.variants]
FreeRAM = { string = "free_ram" }
CPUload = { string = "cpu_load" }
