[CPEInterfaceType]
[CPEInterfaceType.variants]
WiFi    = "wifi"
Wired   = "wired"

[ConfigurationStatus]
[ConfigurationStatus.variants]
Empty    = "empty"
Error    = "error"
OK       = "ok"
Pending  = "pending"
Updating = "updating"

[Module]
[Module.variants]
Any        = "+"
Dummy      = "DUMMY"
Backend    = "BACKEND"
CPE        = "CPE"
Config     = "CONFIG"
DB         = "DB"
Stat       = "STAT"
Monitor    = "MONITOR"
LBS        = "LBS"
ClientStat = "CLIENT_STAT"
MQTTLog    = "MQTT_LOG"
CPEStat    = "CPE_STAT"
AC         = "AC"

[Operation]
[Operation.variants]
Any       = "+"
Create    = "C"
Delete    = "D"
Read      = "R"
Update    = "U"
LuaScript = "LUA"
SHScript  = "SH"
CPEStatus = "STATUS"

[SystemEventType]
[SystemEventType.variants]
Any                     = "+"
CPEConnected            = "CPE_CONNECTED"
CPEDisconnected         = "CPE_DISCONNECTED"
MonitorRuleViolation    = "MONITOR_RULE_VIOLATION"
CPEConfigurationError   = "CPE_CONFIGURATION_ERROR"
CPEConfigurationSuccess = "CPE_CONFIGURATION_SUCCESS"
ClientConnected         = "CLIENT_CONNECTED"
ClientDisconnected      = "CLIENT_DISCONNECTED"
ServiceFatalError       = "SERVICE_FATAL_ERROR"
ServiceConnected        = "SERVICE_CONNECTED"
ServiceDisconnected     = "SERVICE_DISCONNECTED"
DaemonSettingsChanged   = "DAEMON_SETTINGS_CHANGE"

[SystemEventLevel]
[SystemEventLevel.variants]
INFO      = "INFO"
DEBUG     = "DEBUG"
ERROR     = "ERROR"
WARNING   = "WARNING"

[RadiusType]
[RadiusType.variants]
Accounting     = "acct"
Authentication = "auth"
Both           = "both"

[SecuritySuite]
[SecuritySuite.variants]
AES  = "aes"
TKIP = "tkip"

[SecurityType]
[SecurityType.variants]
WPA2Enterprise = "wpa2enterprise"
WPA2Personal   = "wpa2personal"
WPAEnterprise = "wpaenterprise"
WPAPersonal   = "wpapersonal"

[CPEAgentStatusType]
[CPEAgentStatusType.variants]
Success     = "success"
Undefined   = "undefined"
SyntaxError = "syntax"
Exception   = "exception"

[StatEventRuleType]
[StatEventRuleType.variants]
FreeRAM = "free_ram"
CPUload = "cpu_load"

[ClientStatPacketType]
[ClientStatPacketType.variants]
On      = "Accounting-On"
Off     = "Accounting-Off"
Start   = "Start"
Stop    = "Stop"
Interim = "Interim-Update"

[BandwidthType]
[BandwidthType.variants]
HT20      = "HT20"
HT40      = "HT40"
HT40Plus  = "HT40+"
HT40Minus = "HT40-"
VHT20     = "VHT20"
VHT40     = "VHT40"
VHT80     = "VHT80"
VHT160    = "VHT160"

[WirelessClientType]
[WirelessClientType.variants]
Camera = "camera"
Other  = "other"

[WirelessClientState]
[WirelessClientState.variants]
CONNECTED     = "CONNECTED"
DISCONNECTED  = "DISCONNECTED"

[MacFilterType]
[MacFilterType.variants]
BlackList = "BlackList"
WhiteList = "WhiteList"
None      = "None"

[ServiceState]
[ServiceState.variants]
Connected    = "CONNECTED"
Disconnected = "DISCONNECTED"
Pending      = "PENDING"
