[PortalUserState]
default = "New"
[PortalUserState.variants]
New            = "new"
Authenticate   = "authenticate"
Authorize      = "authorize"
Advertise      = "advertise"
Pass           = "pass"

[PortalAuthenticationType]
default = "SMS"
[PortalAuthenticationType.variants]
None     = "none"
SMS      = "sms"
Callback = "callback"
Voucher  = "voucher"
UserPass = "userpass"
ESIA     = "esia"
Email    = "email"

[PortalAuthorizationType]
default = "None"
[PortalAuthorizationType.variants]
None     = "none"
Free     = "free"
Sponsor  = "sponsor" 
Voucher  = "voucher"
ExtVoucher = "ext_voucher"
Staff    = "staff"

[PortalAuthenticationState]
default = "Need"
[PortalAuthenticationState.variants]
Need    = "need"
Sent    = "sent"
Checked = "checked"

[PortalAuthorizationState]
default = "Need"
[PortalAuthorizationState.variants]
Need    = "none"
Checked = "checked"

[PortalAdvertisementState]
default = "Need"
[PortalAdvertisementState.variants]
Need    = "none"
Checked = "checked"

[PortalResponseStatus]
default = "Success"
[PortalResponseStatus.variants]
Success = "success"
Error   = "error"

[PortalAdvertisementType]
default = "Image"
[PortalAdvertisementType.variants]
Image  = "image"
Video  = "video"
Flash  = "flash"
Iframe = "iframe"
Poll   = "poll"
PollIm = "poll_image"
